/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.config.Session;
import com.equinox.controller.ControllerBelanja;
import com.equinox.controller.ControllerKasir;
import com.equinox.model.Kasir;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class BelanjaForm extends javax.swing.JFrame implements ActionListener {

    private ControllerBelanja controllerBelanja;

    public BelanjaForm() {
        if (Session.getStatusLoginAdmin() == "AKTIF") {
            initComponents();
            setSize(602, 732);
            setLocationRelativeTo(null);
            controllerBelanja = new ControllerBelanja(this);
            controllerBelanja.tampilanAwal();
        } else {
            dispose();
            new LoginForm().setVisible(true);
        }
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JLabel getLb_kasir() {
        return lb_kasir;
    }

    public JLabel getBtn_edit() {
        return btn_edit;
    }

    public JLabel getBtn_hapus() {
        return btn_hapus;
    }

    public JLabel getBtn_kembali() {
        return btn_kembali;
    }

    public JLabel getBtn_reset() {
        return btn_reset;
    }

    public JLabel getBtn_simpan() {
        return btn_simpan;
    }

    public JLabel getBtn_tambah() {
        return btn_tambah;
    }

    public JTable getTb_penjualan() {
        return tb_belanja;
    }

    public JTextField getTf_harga() {
        return tf_harga;
    }

    public JTextField getTf_jumlah() {
        return tf_jumlah;
    }

    public JTextField getTf_total() {
        return tf_jumlahharga;
    }

    public JTextField getTf_transaksi() {
        return tf_transaksi;
    }

    public JComboBox<String> getCbx_barang() {
        return cbx_barang;
    }

    public JTextField getTf_jumlahharga() {
        return tf_jumlahharga;
    }

    public JTextField getTf_totalharga() {
        return tf_totalharga;
    }

    public JComboBox<String> getCbx_supplier() {
        return cbx_supplier;
    }

    public JTable getTb_belanja() {
        return tb_belanja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lb_kasir = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_belanja = new javax.swing.JTable();
        tf_transaksi = new javax.swing.JTextField();
        tf_jumlahharga = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        tf_jumlah = new javax.swing.JTextField();
        cbx_barang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tf_totalharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_supplier = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_reset = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel3.setText("Master Buah atau Sayur");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_kasir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_kasir.setForeground(new java.awt.Color(254, 254, 254));
        lb_kasir.setText("Hi, Kasir ^_^");
        getContentPane().add(lb_kasir);
        lb_kasir.setBounds(10, 10, 110, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setForeground(new java.awt.Color(254, 254, 254));
        lb_date.setText("Tanggal-Bulan-Tahun");
        getContentPane().add(lb_date);
        lb_date.setBounds(440, 10, 150, 18);

        jLabel5.setText("No. Transaksi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 110, 92, 17);

        jLabel7.setText("Jenis");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 160, 36, 17);

        jLabel8.setText("Jumlah ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 220, 54, 17);

        jLabel9.setText("Harga per barang");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 220, 121, 17);

        jLabel10.setText("Jumlah Harga  ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 270, 102, 17);

        tb_belanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_belanja.setRowSelectionAllowed(false);
        tb_belanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_belanjaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_belanja);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 360, 457, 216);
        getContentPane().add(tf_transaksi);
        tf_transaksi.setBounds(420, 100, 110, 37);
        getContentPane().add(tf_jumlahharga);
        tf_jumlahharga.setBounds(180, 260, 350, 37);

        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });
        tf_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_hargaKeyReleased(evt);
            }
        });
        getContentPane().add(tf_harga);
        tf_harga.setBounds(440, 210, 88, 37);

        tf_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jumlahActionPerformed(evt);
            }
        });
        tf_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(tf_jumlah);
        tf_jumlah.setBounds(180, 210, 111, 37);

        cbx_barang.setToolTipText("-- Pilih --");
        cbx_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_barangMouseClicked(evt);
            }
        });
        cbx_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_barangActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_barang);
        cbx_barang.setBounds(180, 150, 120, 37);

        jLabel1.setText("Total Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 600, 81, 17);
        getContentPane().add(tf_totalharga);
        tf_totalharga.setBounds(310, 590, 216, 37);

        jLabel4.setText("Supplier");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 120, 57, 17);

        getContentPane().add(cbx_supplier);
        cbx_supplier.setBounds(180, 100, 117, 37);

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_tambah.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(70, 310, 110, 40);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_edit.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(190, 310, 110, 40);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_hapus.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(310, 310, 110, 40);

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_reset.png"))); // NOI18N
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(420, 310, 110, 40);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_simpan.png"))); // NOI18N
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(420, 650, 106, 40);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button kembali.png"))); // NOI18N
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(300, 650, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/4 polos.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-1, -3, 602, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_barangMouseClicked

    }//GEN-LAST:event_cbx_barangMouseClicked

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed

    }//GEN-LAST:event_tf_hargaActionPerformed

    private void cbx_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_barangActionPerformed

    }//GEN-LAST:event_cbx_barangActionPerformed

    private void tf_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jumlahActionPerformed

    }//GEN-LAST:event_tf_jumlahActionPerformed

    private void tb_belanjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_belanjaMouseClicked
        controllerBelanja.getDataField();
        controllerBelanja.setKomponen("clicked");
    }//GEN-LAST:event_tb_belanjaMouseClicked

    private void tf_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyTyped

    }//GEN-LAST:event_tf_jumlahKeyTyped

    private void tf_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyReleased
        controllerBelanja.getJumlahHarga();
    }//GEN-LAST:event_tf_jumlahKeyReleased

    private void tf_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hargaKeyReleased
        controllerBelanja.getJumlahHarga();
    }//GEN-LAST:event_tf_hargaKeyReleased

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        controllerBelanja.tambah();
        controllerBelanja.isiTabel();
        controllerBelanja.getTotalHarga();
        controllerBelanja.reset();
        controllerBelanja.setKomponen("added");
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        controllerBelanja.edit();
        controllerBelanja.reset();
        controllerBelanja.setKomponen("edited");
        controllerBelanja.isiTabel();
        controllerBelanja.getTotalHarga();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        controllerBelanja.hapus();
        controllerBelanja.reset();
        controllerBelanja.setKomponen("deleted");
        controllerBelanja.isiTabel();
        controllerBelanja.getTotalHarga();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        controllerBelanja.reset();
        controllerBelanja.setKomponen("reseted");
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        controllerBelanja.simpan();
        controllerBelanja.tampilanAwal();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        controllerBelanja.kembali();
    }//GEN-LAST:event_btn_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BelanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BelanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BelanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BelanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BelanjaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JComboBox<String> cbx_barang;
    private javax.swing.JComboBox<String> cbx_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_kasir;
    private javax.swing.JTable tb_belanja;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_jumlahharga;
    private javax.swing.JTextField tf_totalharga;
    private javax.swing.JTextField tf_transaksi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

    }
}
