/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.config.Session;
import com.equinox.controller.ControllerKasir;
import com.equinox.model.Kasir;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class FormKasir extends javax.swing.JFrame implements ActionListener {

    private ControllerKasir controllerKasir;
    private LoginForm login;

    public FormKasir() {
        if (Session.getStatusLoginKasir() == "AKTIF") {
            initComponents();
            setSize(602,700);
            setLocationRelativeTo(null);
            controllerKasir = new ControllerKasir(this);
            controllerKasir.tampilanKasir();
        } else {
            dispose();
           new LoginForm().setVisible(true);
        }
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JLabel getLb_kasir() {
        return lb_kasir;
    }

    public JLabel getBtn_edit() {
        return btn_edit;
    }

    public JLabel getBtn_hapus() {
        return btn_hapus;
    }

    public JLabel getBtn_kembali() {
        return btn_kembali;
    }

    public JLabel getBtn_reset() {
        return btn_reset;
    }

    public JLabel getBtn_simpan() {
        return btn_simpan;
    }

    public JLabel getBtn_tambah() {
        return btn_tambah;
    }

    public JTable getTb_penjualan() {
        return tb_penjualan;
    }

    public JTextField getTf_harga() {
        return tf_harga;
    }

    public JTextField getTf_jumlah() {
        return tf_jumlah;
    }

    public JTextField getTf_total() {
        return tf_jumlahharga;
    }

    public JTextField getTf_transaksi() {
        return tf_transaksi;
    }

    public JComboBox<String> getCbx_barang() {
        return cbx_barang;
    }
    
    public JTextField getTf_jumlahharga() {
        return tf_jumlahharga;
    }

    public JTextField getTf_totalharga() {
        return tf_totalharga;
    }

    public JTextArea getTf_alamat() {
        return tf_alamat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lb_kasir = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penjualan = new javax.swing.JTable();
        tf_transaksi = new javax.swing.JTextField();
        tf_jumlahharga = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        tf_jumlah = new javax.swing.JTextField();
        cbx_barang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tf_totalharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_alamat = new javax.swing.JTextArea();
        Btn_editharga = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        btn_reset = new javax.swing.JLabel();
        btn_pesanan = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel3.setText("Master Buah atau Sayur");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_kasir.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_kasir.setForeground(new java.awt.Color(254, 254, 254));
        lb_kasir.setText("Hi, Kasir ^_^");
        getContentPane().add(lb_kasir);
        lb_kasir.setBounds(20, 0, 120, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setForeground(new java.awt.Color(254, 254, 254));
        lb_date.setText("Tanggal-Bulan-Tahun");
        getContentPane().add(lb_date);
        lb_date.setBounds(440, 0, 150, 18);

        jLabel5.setText("No. Transaksi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 92, 17);

        jLabel7.setText("Barang");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 190, 50, 17);

        jLabel8.setText("Jumlah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 240, 51, 17);

        jLabel9.setText("Harga per barang Rp.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 240, 145, 17);

        jLabel10.setText("Jumlah Harga   Rp.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 290, 126, 17);

        tb_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_penjualan.setRowSelectionAllowed(false);
        tb_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_penjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_penjualan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 390, 536, 120);
        getContentPane().add(tf_transaksi);
        tf_transaksi.setBounds(160, 130, 180, 37);
        getContentPane().add(tf_jumlahharga);
        tf_jumlahharga.setBounds(160, 280, 386, 37);

        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });
        tf_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_hargaKeyReleased(evt);
            }
        });
        getContentPane().add(tf_harga);
        tf_harga.setBounds(440, 230, 88, 37);

        tf_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jumlahActionPerformed(evt);
            }
        });
        tf_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(tf_jumlah);
        tf_jumlah.setBounds(160, 230, 111, 37);

        cbx_barang.setToolTipText("-- Pilih --");
        cbx_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_barangMouseClicked(evt);
            }
        });
        cbx_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_barangActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_barang);
        cbx_barang.setBounds(160, 180, 180, 37);

        jLabel1.setText("Total Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 530, 81, 17);
        getContentPane().add(tf_totalharga);
        tf_totalharga.setBounds(440, 520, 120, 37);

        jLabel6.setText("Alamat Pengantaran");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 520, 141, 17);

        tf_alamat.setColumns(20);
        tf_alamat.setRows(5);
        tf_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_alamatKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tf_alamat);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 540, 231, 70);

        Btn_editharga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/4.gak tau nih button apaan.png"))); // NOI18N
        Btn_editharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_edithargaMouseClicked(evt);
            }
        });
        getContentPane().add(Btn_editharga);
        Btn_editharga.setBounds(540, 230, 30, 30);

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_tambah.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(30, 340, 110, 40);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_edit.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(140, 340, 110, 40);

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_reset.png"))); // NOI18N
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(360, 340, 110, 40);

        btn_pesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_pesanan.png"))); // NOI18N
        btn_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pesananMouseClicked(evt);
            }
        });
        getContentPane().add(btn_pesanan);
        btn_pesanan.setBounds(470, 340, 110, 40);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_hapus.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(250, 340, 110, 40);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_logout.png"))); // NOI18N
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(340, 610, 110, 40);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_simpan.png"))); // NOI18N
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(460, 610, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/4 polos.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(602, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_barangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_barangMouseClicked

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed

    }//GEN-LAST:event_tf_hargaActionPerformed

    private void cbx_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_barangActionPerformed
        controllerKasir.setKomponen("editHargaDisable");
        controllerKasir.getHarga();
    }//GEN-LAST:event_cbx_barangActionPerformed

    private void tf_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jumlahActionPerformed
        controllerKasir.getHarga();
    }//GEN-LAST:event_tf_jumlahActionPerformed

    private void tb_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_penjualanMouseClicked
        controllerKasir.getDataField();
        controllerKasir.setKomponen("clicked");
    }//GEN-LAST:event_tb_penjualanMouseClicked

    private void tf_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyTyped

    }//GEN-LAST:event_tf_jumlahKeyTyped

    private void tf_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyReleased
        controllerKasir.getJumlahHarga();
        controllerKasir.cekStok();
    }//GEN-LAST:event_tf_jumlahKeyReleased

    private void tf_alamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_alamatKeyReleased
        controllerKasir.getTotalHarga();
    }//GEN-LAST:event_tf_alamatKeyReleased

    private void Btn_edithargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_edithargaMouseClicked
        controllerKasir.setKomponen("editHargaEnable");
    }//GEN-LAST:event_Btn_edithargaMouseClicked

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        controllerKasir.setKomponen("added");
        controllerKasir.tambah();
        controllerKasir.isiTabel();
        controllerKasir.getTotalHarga();
        controllerKasir.reset();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        controllerKasir.setKomponen("edited");
        controllerKasir.edit();
        controllerKasir.isiTabel();
        controllerKasir.getTotalHarga();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        controllerKasir.setKomponen("deleted");
        controllerKasir.hapus();
        controllerKasir.isiTabel();
        controllerKasir.getTotalHarga();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        controllerKasir.reset();
        controllerKasir.setKomponen("reseted");
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pesananMouseClicked
        this.setVisible(false);
        new FormConfirmPesanan().setVisible(true);
    }//GEN-LAST:event_btn_pesananMouseClicked

    private void tf_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_hargaKeyReleased
        controllerKasir.getJumlahHarga();
    }//GEN-LAST:event_tf_hargaKeyReleased

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        controllerKasir.Logout();
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        controllerKasir.insert();
    }//GEN-LAST:event_btn_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btn_editharga;
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_pesanan;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JComboBox<String> cbx_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_kasir;
    private javax.swing.JTable tb_penjualan;
    private javax.swing.JTextArea tf_alamat;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_jumlahharga;
    private javax.swing.JTextField tf_totalharga;
    private javax.swing.JTextField tf_transaksi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {

    }
}
