/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.controller.ControllerConfirmPesanan;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class FormConfirmPesanan extends javax.swing.JFrame {

    private ControllerConfirmPesanan confirmPesanan;

    public FormConfirmPesanan() {
        initComponents();
        setSize(900, 580);
        setLocationRelativeTo(null);
        confirmPesanan = new ControllerConfirmPesanan(this);
    }

    public JLabel getBt_confirm() {
        return bt_confirm;
    }

    public JLabel getBt_kembali() {
        return bt_kembali;
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JLabel getLb_kasir1() {
        return lb_kasir1;
    }

    public JTable getTb_detailPesanan() {
        return tb_detailPesanan;
    }

    public JTable getTb_listPesanan() {
        return tb_listPesanan;
    }

    public JTextField getTf_idPesanan() {
        return tf_idPesanan;
    }

    public JTextField getTf_jumlahItem() {
        return tf_jumlahItem;
    }

    public JTextField getTf_namaToko() {
        return tf_namaToko;
    }

    public JTextField getTf_tanggal() {
        return tf_tanggal;
    }

    public JTextField getTf_totalHarga() {
        return tf_totalHarga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lb_kasir1 = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_idPesanan = new javax.swing.JTextField();
        tf_namaToko = new javax.swing.JTextField();
        tf_tanggal = new javax.swing.JTextField();
        tf_jumlahItem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_detailPesanan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_listPesanan = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        tf_totalHarga = new javax.swing.JTextField();
        bt_kembali = new javax.swing.JLabel();
        bt_confirm = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_kasir1.setText("Hi, Kasir ^_^");
        getContentPane().add(lb_kasir1);
        lb_kasir1.setBounds(12, 12, 110, 17);

        lb_date.setText("Hari-Tanggal-Bulan");
        getContentPane().add(lb_date);
        lb_date.setBounds(740, 10, 140, 17);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("TRANSAKSI PESANAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 50, 170, 18);

        jLabel2.setText("Id Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 80, 17);

        jLabel3.setText("Tanggal Memesan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 130, 17);

        jLabel4.setText("Jumlah Item (qty)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 230, 130, 17);

        jLabel5.setText("Nama Toko");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 90, 17);
        getContentPane().add(tf_idPesanan);
        tf_idPesanan.setBounds(180, 100, 270, 37);
        getContentPane().add(tf_namaToko);
        tf_namaToko.setBounds(180, 140, 270, 37);
        getContentPane().add(tf_tanggal);
        tf_tanggal.setBounds(180, 180, 270, 37);
        getContentPane().add(tf_jumlahItem);
        tf_jumlahItem.setBounds(180, 220, 270, 37);

        jLabel6.setText("Detail Pesanan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 280, 110, 17);

        tb_detailPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_detailPesanan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 310, 410, 120);

        jLabel7.setText("List Pesanan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 100, 100, 17);

        tb_listPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_listPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listPesananMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_listPesanan);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(500, 130, 380, 340);

        jLabel8.setText("Total Harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 450, 90, 17);
        getContentPane().add(tf_totalHarga);
        tf_totalHarga.setBounds(276, 440, 180, 37);

        bt_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button kembali.png"))); // NOI18N
        bt_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(bt_kembali);
        bt_kembali.setBounds(770, 480, 110, 40);

        bt_confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button konfirmasi.png"))); // NOI18N
        bt_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_confirmMouseClicked(evt);
            }
        });
        getContentPane().add(bt_confirm);
        bt_confirm.setBounds(350, 490, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_listPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listPesananMouseClicked
        confirmPesanan.getDataField();
    }//GEN-LAST:event_tb_listPesananMouseClicked

    private void bt_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_kembaliMouseClicked
        this.setVisible(false);
        new FormKasir().setVisible(true);
    }//GEN-LAST:event_bt_kembaliMouseClicked

    private void bt_confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_confirmMouseClicked
        confirmPesanan.confirmPesanan();
        confirmPesanan.isiTabelPesanan();
    }//GEN-LAST:event_bt_confirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConfirmPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConfirmPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConfirmPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConfirmPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConfirmPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_confirm;
    private javax.swing.JLabel bt_kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_kasir1;
    private javax.swing.JTable tb_detailPesanan;
    private javax.swing.JTable tb_listPesanan;
    private javax.swing.JTextField tf_idPesanan;
    private javax.swing.JTextField tf_jumlahItem;
    private javax.swing.JTextField tf_namaToko;
    private javax.swing.JTextField tf_tanggal;
    private javax.swing.JTextField tf_totalHarga;
    // End of variables declaration//GEN-END:variables
}
