/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.controller.ControllerTokoLangganan;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class FormTokoLangganan extends javax.swing.JFrame {

    private ControllerTokoLangganan controllerTokoLangganan;
    
    public FormTokoLangganan() {
        initComponents();
        setSize(945, 622);
        setLocationRelativeTo(null);
        controllerTokoLangganan = new ControllerTokoLangganan(this);
        controllerTokoLangganan.tampilanAwal();
    }

    public JLabel getBtn_edit() {
        return btn_edit;
    }

    public JLabel getBtn_hapus() {
        return btn_hapus;
    }

    public JLabel getBtn_kembali() {
        return btn_kembali;
    }

    public JLabel getBtn_reset() {
        return btn_reset;
    }

    public JLabel getBtn_simpan() {
        return btn_simpan;
    }

    public JLabel getBtn_tambah() {
        return btn_tambah;
    }

    public JComboBox<String> getCbx_barang() {
        return cbx_barang;
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JLabel getLb_toko() {
        return lb_toko;
    }

    public JTable getTb_detailPesanan() {
        return tb_detailPesanan;
    }

    public JTable getTb_keranjangPesanan() {
        return tb_keranjangPesanan;
    }

    public JTable getTb_listPesanan() {
        return tb_listPesanan;
    }

    public JTextField getTf_harga() {
        return tf_harga;
    }

    public JTextField getTf_idPesanan() {
        return tf_idPesanan;
    }

    public JTextField getTf_jumlah() {
        return tf_jumlah;
    }

    public JTextField getTf_jumlahHarga() {
        return tf_jumlahHarga;
    }

    public JTextField getTf_totalHarga() {
        return tf_totalHarga;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_toko = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listPesanan = new javax.swing.JTable();
        tf_idPesanan = new javax.swing.JTextField();
        cbx_barang = new javax.swing.JComboBox<>();
        tf_jumlah = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        tf_jumlahHarga = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JLabel();
        btn_edit = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JLabel();
        btn_reset = new javax.swing.JLabel();
        btn_kembali = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_keranjangPesanan = new javax.swing.JTable();
        tf_totalHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_detailPesanan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_toko.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_toko.setText("Hi, Toko ^_^");
        getContentPane().add(lb_toko);
        lb_toko.setBounds(12, 12, 120, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setText("Tanggal-Bulan-Tahun");
        getContentPane().add(lb_date);
        lb_date.setBounds(762, 10, 170, 18);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Id Transaksi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 90, 18);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 120, 50, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Jumlah");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 60, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Jumlah Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 100, 18);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Harga per barang");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 170, 130, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("List Pesanan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 130, 90, 18);

        tb_listPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_listPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listPesanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 160, 400, 140);
        getContentPane().add(tf_idPesanan);
        tf_idPesanan.setBounds(140, 110, 60, 37);

        cbx_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbx_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_barangActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_barang);
        cbx_barang.setBounds(290, 110, 150, 37);

        tf_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jumlahKeyReleased(evt);
            }
        });
        getContentPane().add(tf_jumlah);
        tf_jumlah.setBounds(140, 160, 110, 37);
        getContentPane().add(tf_harga);
        tf_harga.setBounds(390, 160, 110, 37);
        getContentPane().add(tf_jumlahHarga);
        tf_jumlahHarga.setBounds(140, 210, 170, 37);

        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_tambah.png"))); // NOI18N
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(btn_tambah);
        btn_tambah.setBounds(40, 260, 110, 40);

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_edit.png"))); // NOI18N
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        getContentPane().add(btn_edit);
        btn_edit.setBounds(150, 260, 110, 40);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_hapus.png"))); // NOI18N
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(btn_hapus);
        btn_hapus.setBounds(260, 260, 110, 40);

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_reset.png"))); // NOI18N
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(370, 260, 110, 40);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_logout.png"))); // NOI18N
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btn_kembali);
        btn_kembali.setBounds(810, 530, 110, 40);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_simpan.png"))); // NOI18N
        btn_simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanMouseClicked(evt);
            }
        });
        getContentPane().add(btn_simpan);
        btn_simpan.setBounds(380, 530, 110, 40);

        tb_keranjangPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_keranjangPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_keranjangPesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_keranjangPesanan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 310, 452, 150);

        tf_totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalHargaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_totalHarga);
        tf_totalHarga.setBounds(326, 470, 160, 37);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Total Harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 480, 90, 18);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Detail Pesanan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 310, 110, 18);

        tb_detailPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_detailPesanan);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(530, 340, 400, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9 asli(1).png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-3, -3, 950, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        controllerTokoLangganan.setKomponen("added");
        controllerTokoLangganan.tambah();
        controllerTokoLangganan.isiKeranjang();
        controllerTokoLangganan.reset();
        controllerTokoLangganan.getTotalHarga();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        controllerTokoLangganan.setKomponen("edited");
        controllerTokoLangganan.edit();
        controllerTokoLangganan.isiKeranjang();
        controllerTokoLangganan.getTotalHarga();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        controllerTokoLangganan.setKomponen("deleted");
        controllerTokoLangganan.hapus();
        controllerTokoLangganan.isiKeranjang();
        controllerTokoLangganan.getTotalHarga();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        controllerTokoLangganan.reset();
        controllerTokoLangganan.setKomponen("reseted");
    }//GEN-LAST:event_btn_resetMouseClicked

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
        this.setVisible(false);
        new Form().setVisible(true);
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanMouseClicked
        controllerTokoLangganan.insert();
        controllerTokoLangganan.tampilanAwal();
    }//GEN-LAST:event_btn_simpanMouseClicked

    private void tf_totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalHargaActionPerformed

    private void cbx_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_barangActionPerformed
        controllerTokoLangganan.getHarga();
    }//GEN-LAST:event_cbx_barangActionPerformed

    private void tf_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_jumlahKeyReleased
        controllerTokoLangganan.cekStok();
        controllerTokoLangganan.getJumlahHarga();
    }//GEN-LAST:event_tf_jumlahKeyReleased

    private void tb_keranjangPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_keranjangPesananMouseClicked
        controllerTokoLangganan.setKomponen("clicked");
        controllerTokoLangganan.getDataField();
        btn_tambah.setEnabled(false);
    }//GEN-LAST:event_tb_keranjangPesananMouseClicked

    private void tb_listPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listPesananMouseClicked
        controllerTokoLangganan.isiTabelDetailPesanan();
    }//GEN-LAST:event_tb_listPesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTokoLangganan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTokoLangganan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTokoLangganan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTokoLangganan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTokoLangganan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_edit;
    private javax.swing.JLabel btn_hapus;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_simpan;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JComboBox<String> cbx_barang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_toko;
    private javax.swing.JTable tb_detailPesanan;
    private javax.swing.JTable tb_keranjangPesanan;
    private javax.swing.JTable tb_listPesanan;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_idPesanan;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_jumlahHarga;
    private javax.swing.JTextField tf_totalHarga;
    // End of variables declaration//GEN-END:variables
}
