/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.config.Session;
import com.equinox.controller.ControllerAdmin;
import com.equinox.model.Admin;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author equinox
 */
public class FormAdmin extends javax.swing.JFrame {

    private ControllerAdmin controllerAdmin;
    private LoginForm login;

    public FormAdmin() {
//        if (Session.getStatusLoginAdmin() == "AKTIF") {
            initComponents();
            setSize(739, 565);
            setLocationRelativeTo(null);
            controllerAdmin = new ControllerAdmin(this);
            controllerAdmin.tampilanAdmin();
//        } else {
//            dispose();
//            new LoginForm().setVisible(true);
//        }
    }

    public JLabel getLb_admin() {
        return lb_admin;
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_admin = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        tb_inputBelanja = new javax.swing.JLabel();
        tb_masterBarang = new javax.swing.JLabel();
        tb_masterKasir = new javax.swing.JLabel();
        tb_masterSupplier = new javax.swing.JLabel();
        tb_masterToko = new javax.swing.JLabel();
        tb_rekapTransaksi = new javax.swing.JLabel();
        bt_logout = new javax.swing.JLabel();
        bt_logLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_admin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(254, 254, 254));
        lb_admin.setText("Hi, Admin ^_^");
        getContentPane().add(lb_admin);
        lb_admin.setBounds(22, 12, 110, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setForeground(new java.awt.Color(254, 254, 254));
        lb_date.setText("Tanggal-Bulan-Tahun");
        getContentPane().add(lb_date);
        lb_date.setBounds(570, 20, 150, 18);

        tb_inputBelanja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button input belanja.png"))); // NOI18N
        tb_inputBelanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_inputBelanjaMouseClicked(evt);
            }
        });
        getContentPane().add(tb_inputBelanja);
        tb_inputBelanja.setBounds(330, 270, 90, 90);

        tb_masterBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button master barang.png"))); // NOI18N
        tb_masterBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_masterBarangMouseClicked(evt);
            }
        });
        getContentPane().add(tb_masterBarang);
        tb_masterBarang.setBounds(170, 280, 90, 80);

        tb_masterKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button master kasir.png"))); // NOI18N
        tb_masterKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_masterKasirMouseClicked(evt);
            }
        });
        getContentPane().add(tb_masterKasir);
        tb_masterKasir.setBounds(170, 380, 90, 80);

        tb_masterSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button master supplier.png"))); // NOI18N
        tb_masterSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_masterSupplierMouseClicked(evt);
            }
        });
        getContentPane().add(tb_masterSupplier);
        tb_masterSupplier.setBounds(490, 380, 90, 80);

        tb_masterToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button toko langganan.png"))); // NOI18N
        tb_masterToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_masterTokoMouseClicked(evt);
            }
        });
        getContentPane().add(tb_masterToko);
        tb_masterToko.setBounds(330, 380, 86, 80);

        tb_rekapTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.button rekap transaksi penjualan.png"))); // NOI18N
        tb_rekapTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_rekapTransaksiMouseClicked(evt);
            }
        });
        getContentPane().add(tb_rekapTransaksi);
        tb_rekapTransaksi.setBounds(490, 270, 90, 80);

        bt_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_logout.png"))); // NOI18N
        bt_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logoutMouseClicked(evt);
            }
        });
        getContentPane().add(bt_logout);
        bt_logout.setBounds(600, 470, 110, 40);

        bt_logLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button log login.png"))); // NOI18N
        bt_logLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logLoginMouseClicked(evt);
            }
        });
        getContentPane().add(bt_logLogin);
        bt_logLogin.setBounds(480, 470, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 739, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_masterBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_masterBarangMouseClicked
        controllerAdmin.masterBarang();
    }//GEN-LAST:event_tb_masterBarangMouseClicked

    private void tb_masterSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_masterSupplierMouseClicked
        controllerAdmin.masterSupplier();
    }//GEN-LAST:event_tb_masterSupplierMouseClicked

    private void tb_rekapTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_rekapTransaksiMouseClicked
        controllerAdmin.rekapTransaksi();
    }//GEN-LAST:event_tb_rekapTransaksiMouseClicked

    private void tb_inputBelanjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_inputBelanjaMouseClicked
        controllerAdmin.transaksiBelanja();
    }//GEN-LAST:event_tb_inputBelanjaMouseClicked

    private void tb_masterKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_masterKasirMouseClicked
        controllerAdmin.masterKasir();
    }//GEN-LAST:event_tb_masterKasirMouseClicked

    private void tb_masterTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_masterTokoMouseClicked
        controllerAdmin.masterTokoPelanggan();
    }//GEN-LAST:event_tb_masterTokoMouseClicked

    private void bt_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logoutMouseClicked
        controllerAdmin.Logout();
    }//GEN-LAST:event_bt_logoutMouseClicked

    private void bt_logLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_logLoginMouseClicked
        this.setVisible(false);
        new FormLogLogin().setVisible(true);
    }//GEN-LAST:event_bt_logLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_logLogin;
    private javax.swing.JLabel bt_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel tb_inputBelanja;
    private javax.swing.JLabel tb_masterBarang;
    private javax.swing.JLabel tb_masterKasir;
    private javax.swing.JLabel tb_masterSupplier;
    private javax.swing.JLabel tb_masterToko;
    private javax.swing.JLabel tb_rekapTransaksi;
    // End of variables declaration//GEN-END:variables

}
