/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.controller.ControllerAdmin;
import com.equinox.controller.ControllerKasir;
import com.equinox.controller.ControllerLogin;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class LoginForm extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private ControllerLogin controllerLogin;

    private String level;

    /**
     * Creates new form Login
     */
    public LoginForm() {
        initComponents();
        setSize(738,565);
        setLocationRelativeTo(null);
        controllerLogin = new ControllerLogin(this);
    }

    public JComboBox<String> getCbx_level() {
        return cbx_level;
    }

    public JPasswordField getTxt_pass() {
        return txt_pass;
    }

    public JTextField getTxt_ussername() {
        return txt_ussername;
    }

    public String getLevel() {
        return level;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ussername = new javax.swing.JTextField();
        cbx_level = new javax.swing.JComboBox<>();
        txt_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txt_ussername.setBackground(new java.awt.Color(63, 61, 86));
        txt_ussername.setForeground(new java.awt.Color(254, 254, 254));
        txt_ussername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ussernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ussername);
        txt_ussername.setBounds(180, 180, 219, 37);

        cbx_level.setBackground(new java.awt.Color(63, 61, 86));
        cbx_level.setForeground(new java.awt.Color(63, 61, 86));
        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kasir", "Toko Langganan" }));
        cbx_level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_levelActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_level);
        cbx_level.setBounds(180, 300, 219, 37);

        txt_pass.setBackground(new java.awt.Color(63, 61, 86));
        txt_pass.setForeground(new java.awt.Color(254, 254, 254));
        getContentPane().add(txt_pass);
        txt_pass.setBounds(180, 240, 219, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/2.button masuk.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 400, 147, 38);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/2.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 740, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ussernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ussernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ussernameActionPerformed

    private void cbx_levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_levelActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        controllerLogin.loginTokoLangganan();
        controllerLogin.loginAdmin();
        controllerLogin.loginKasir();
    }//GEN-LAST:event_jLabel1MouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_ussername;
    // End of variables declaration//GEN-END:variables
}
