/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.config.Session;
import com.equinox.controller.ControllerBarang;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class MasterBarangForm extends javax.swing.JFrame implements ActionListener {

    private ControllerBarang controllerBarang;

    public MasterBarangForm() {
        if (Session.getStatusLoginAdmin() == "AKTIF") {
            initComponents();
            setSize(480,636);
            setLocationRelativeTo(null);
            controllerBarang = new ControllerBarang(this);
            controllerBarang.tampilanAwal();
        } else {
            dispose();
            new LoginForm().setVisible(true);
        }
    }

    public JLabel getLb_admin() {
        return lb_admin;
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JTextField getTf_id() {
        return tf_idbarang;
    }

    public JTextField getTf_harga() {
        return tf_harga;
    }

    public JTextField getTf_nama() {
        return tf_nama;
    }

    public JTextField getTf_stok() {
        return tf_stok;
    }

    public JTable getTb_barang() {
        return tb_barang;
    }

    public JLabel getBt_edit() {
        return bt_edit;
    }

    public JLabel getBt_kembali() {
        return bt_kembali;
    }

    public JLabel getBt_reset() {
        return bt_reset;
    }

    public JLabel getBt_tambah() {
        return bt_tambah;
    }

    public JTextField getTf_idbarang() {
        return tf_idbarang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_admin = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        tf_stok = new javax.swing.JTextField();
        tf_idbarang = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_barang = new javax.swing.JTable();
        bt_tambah = new javax.swing.JLabel();
        bt_edit = new javax.swing.JLabel();
        bt_reset = new javax.swing.JLabel();
        bt_kembali = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_admin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(68, 168, 95));
        lb_admin.setText("Hi, Admin ^_^");
        getContentPane().add(lb_admin);
        lb_admin.setBounds(20, 12, 120, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setForeground(new java.awt.Color(68, 168, 95));
        lb_date.setText("Hari-Tanggal-Bulan");
        getContentPane().add(lb_date);
        lb_date.setBounds(340, 10, 140, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Id Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 90, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Nama ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 70, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Harga satuan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 260, 120, 18);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Stok awal ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 100, 18);
        getContentPane().add(tf_nama);
        tf_nama.setBounds(150, 200, 183, 37);

        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_harga);
        tf_harga.setBounds(150, 250, 183, 37);
        getContentPane().add(tf_stok);
        tf_stok.setBounds(150, 300, 183, 37);

        tf_idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tf_idbarang);
        tf_idbarang.setBounds(150, 150, 183, 37);

        tb_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_barangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_barang);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(16, 361, 452, 170);

        bt_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_tambah.png"))); // NOI18N
        bt_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(bt_tambah);
        bt_tambah.setBounds(350, 160, 110, 40);

        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_edit.png"))); // NOI18N
        bt_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_editMouseClicked(evt);
            }
        });
        getContentPane().add(bt_edit);
        bt_edit.setBounds(350, 220, 110, 40);

        bt_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_reset.png"))); // NOI18N
        bt_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_resetMouseClicked(evt);
            }
        });
        getContentPane().add(bt_reset);
        bt_reset.setBounds(350, 280, 110, 40);

        bt_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button kembali.png"))); // NOI18N
        bt_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(bt_kembali);
        bt_kembali.setBounds(360, 550, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/7 asli.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1, -3, 480, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idbarangActionPerformed

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hargaActionPerformed

    private void tb_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_barangMouseClicked
        controllerBarang.getDataField();
        controllerBarang.setKomponen("clicked");
    }//GEN-LAST:event_tb_barangMouseClicked

    private void bt_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahMouseClicked
        controllerBarang.insertBarang();
        controllerBarang.isiTabel();
        controllerBarang.reset();
        controllerBarang.setKomponen("added");
        controllerBarang.tampilanAwal();
    }//GEN-LAST:event_bt_tambahMouseClicked

    private void bt_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editMouseClicked
        controllerBarang.setKomponen("edited");
        controllerBarang.update();
        controllerBarang.isiTabel();
        controllerBarang.reset();
        controllerBarang.tampilanAwal();
    }//GEN-LAST:event_bt_editMouseClicked

    private void bt_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_resetMouseClicked
        controllerBarang.reset();
        controllerBarang.setKomponen("reseted");
        controllerBarang.tampilanAwal();
    }//GEN-LAST:event_bt_resetMouseClicked

    private void bt_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_kembaliMouseClicked
        controllerBarang.kembali();
    }//GEN-LAST:event_bt_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBarangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBarangForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_edit;
    private javax.swing.JLabel bt_kembali;
    private javax.swing.JLabel bt_reset;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_date;
    private javax.swing.JTable tb_barang;
    private javax.swing.JTextField tf_harga;
    private javax.swing.JTextField tf_idbarang;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_stok;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
