/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equinox.view;

import com.equinox.config.Session;
import com.equinox.controller.ControllerSupplier;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author equinox
 */
public class MasterSuplierForm extends javax.swing.JFrame {
    
    private ControllerSupplier controllerSupplier;
    
    public MasterSuplierForm() {
        if (Session.getStatusLoginAdmin() == "AKTIF") {
            initComponents();
            setSize(466, 555);
            setLocationRelativeTo(null);
            controllerSupplier = new ControllerSupplier(this);
            controllerSupplier.tampilanAwal();
        } else {
            dispose();
            new LoginForm().setVisible(true);
        }
    }
    
    public JLabel getLb_admin() {
        return lb_admin;
    }
    
    public JLabel getLb_date() {
        return lb_date;
    }
    
    public JTable getTb_supplier() {
        return tb_supplier;
    }
    
    public JTextField getTf_alamat() {
        return tf_alamat;
    }
    
    public JTextField getTf_idSupplier() {
        return tf_idSupplier;
    }
    
    public JTextField getTf_nama() {
        return tf_nama;
    }
    
    public JTextField getTf_notelp() {
        return tf_notelp;
    }
    
    public JLabel getBt_edit() {
        return bt_edit;
    }
    
    public JLabel getBt_hapus() {
        return bt_hapus;
    }
    
    public JLabel getBt_kembali() {
        return bt_kembali;
    }
    
    public JLabel getBt_reset() {
        return bt_reset;
    }
    
    public JLabel getBt_tambah() {
        return bt_tambah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_admin = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_idSupplier = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_alamat = new javax.swing.JTextField();
        tf_notelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_supplier = new javax.swing.JTable();
        bt_tambah = new javax.swing.JLabel();
        bt_hapus = new javax.swing.JLabel();
        bt_edit = new javax.swing.JLabel();
        bt_reset = new javax.swing.JLabel();
        bt_kembali = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lb_admin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_admin.setForeground(new java.awt.Color(68, 168, 95));
        lb_admin.setText("Hi, Admin ^_^");
        getContentPane().add(lb_admin);
        lb_admin.setBounds(12, 12, 120, 18);

        lb_date.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_date.setForeground(new java.awt.Color(68, 168, 95));
        lb_date.setText("Tanggal-Bulan-Tahun");
        getContentPane().add(lb_date);
        lb_date.setBounds(310, 10, 150, 20);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Id Supplier");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 130, 110, 18);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Nama ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 80, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 230, 80, 18);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("No. telp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 280, 90, 18);
        getContentPane().add(tf_idSupplier);
        tf_idSupplier.setBounds(120, 120, 184, 37);
        getContentPane().add(tf_nama);
        tf_nama.setBounds(120, 170, 184, 37);

        tf_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_alamatActionPerformed(evt);
            }
        });
        getContentPane().add(tf_alamat);
        tf_alamat.setBounds(120, 220, 184, 37);
        getContentPane().add(tf_notelp);
        tf_notelp.setBounds(120, 270, 184, 37);

        tb_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_supplier);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(28, 323, 415, 130);

        bt_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_tambah.png"))); // NOI18N
        bt_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahMouseClicked(evt);
            }
        });
        getContentPane().add(bt_tambah);
        bt_tambah.setBounds(320, 140, 110, 40);

        bt_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_hapus.png"))); // NOI18N
        bt_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusMouseClicked(evt);
            }
        });
        getContentPane().add(bt_hapus);
        bt_hapus.setBounds(320, 180, 110, 40);

        bt_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_edit.png"))); // NOI18N
        bt_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_editMouseClicked(evt);
            }
        });
        getContentPane().add(bt_edit);
        bt_edit.setBounds(320, 220, 110, 40);

        bt_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/button_reset.png"))); // NOI18N
        bt_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_resetMouseClicked(evt);
            }
        });
        getContentPane().add(bt_reset);
        bt_reset.setBounds(320, 260, 110, 40);

        bt_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/9.button kembali.png"))); // NOI18N
        bt_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_kembaliMouseClicked(evt);
            }
        });
        getContentPane().add(bt_kembali);
        bt_kembali.setBounds(350, 470, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/equinox/view/image/5 asli.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-1, -3, 470, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_alamatActionPerformed

    private void tb_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_supplierMouseClicked
        controllerSupplier.getDataField();
        controllerSupplier.setKomponen("clicked");
    }//GEN-LAST:event_tb_supplierMouseClicked

    private void bt_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahMouseClicked
        controllerSupplier.insert();
        controllerSupplier.isiTabel();
        controllerSupplier.tampilanAwal();
        controllerSupplier.reset();
        controllerSupplier.setKomponen("added");
    }//GEN-LAST:event_bt_tambahMouseClicked

    private void bt_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusMouseClicked
        controllerSupplier.hapus();
        controllerSupplier.isiTabel();
        controllerSupplier.reset();
        controllerSupplier.setKomponen("deleted");
    }//GEN-LAST:event_bt_hapusMouseClicked

    private void bt_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_editMouseClicked
        controllerSupplier.update();
        controllerSupplier.isiTabel();
        controllerSupplier.reset();
        controllerSupplier.setKomponen("edited");
    }//GEN-LAST:event_bt_editMouseClicked

    private void bt_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_resetMouseClicked
        controllerSupplier.tampilanAwal();
        controllerSupplier.reset();
        controllerSupplier.setKomponen("reseted");
    }//GEN-LAST:event_bt_resetMouseClicked

    private void bt_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_kembaliMouseClicked
        controllerSupplier.kembali();
    }//GEN-LAST:event_bt_kembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterSuplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterSuplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterSuplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterSuplierForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterSuplierForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bt_edit;
    private javax.swing.JLabel bt_hapus;
    private javax.swing.JLabel bt_kembali;
    private javax.swing.JLabel bt_reset;
    private javax.swing.JLabel bt_tambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_date;
    private javax.swing.JTable tb_supplier;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_idSupplier;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_notelp;
    // End of variables declaration//GEN-END:variables
}
